acme/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls import handler404, handler500
from . import views
import debug_toolbar
from django.conf import settings

handler404 = 'acme.views.handler404'
handler500 = 'acme.views.handler500'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/',views.about, name='about'),
    path('contact/',views.contact, name='contact'),
    path('blog/',include('blog.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.show,name='show')
]

blog/models.py
from django.db import models


class TimespamtedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Post(TimespamtedModel):
    title = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.title

acme/views.py
from django.shortcuts import render

def home(request):
    return render(request,'pages/home.html')

def about(request):
    return render(request,'pages/about.html')

def contact(request):
    return render(request,'pages/contact.html')

def handler404(request,exception=None):
    return render(request,'errors/404.html', status=404)

def handler500(request,exception=None):
    return render(request,'errors/500.html', status=500)

blog/views.py
from django.shortcuts import render, get_object_or_404
from . models import Post
from django.http import Http404
# from . mocks import Post


def index(request):
    posts = Post.objects.all()
    return render(request, 'blog/index.html', {'posts': posts})


def show(request, id):
    post = get_object_or_404(Post,pk=id)
    # try:
    #     post = Post.objects.get(pk=id)
    # except Post.DoesNotExist:
    #     raise Http404('Sorry, Post #{} not found.'.format(id))

    return render(request, 'blog/show.html', {'post': post})

blog/templates/blog/base.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'blog/css/styles.css' %}">
{% endblock %}

{% block content %}  
    <h1>Blog</h1>
    {% block body %}
      
    {% endblock %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}Blog{% endblock %}

{% block body %}
    <h2>{{ posts|length }} Posts</h2>
    <ul>
        {% for post in posts  %}
            <article>
                <h2 class="title">
                    <a href="{% url 'blog:show' post.id %}">#{{ post.id }}-{{ post.title|upper }}</a>
                </h2>
                <p class="time">
                    <time datetime="{{ post.created_at|date:'Y-m-d' }}">Posted  {{ post.created_at|timesince }} ago</time>
                </p>
                <p class="content">{{ post.body|truncatewords:3 }}</p>
            </article>
        {% empty %}
            <p>Sorry, no post available</p>
        {% endfor %}    
    </ul>
{% endblock %}    

blog/templates/blog/show.html
{% extends 'blog/base.html' %}

{% block title %}Blog | {{ post.title }}{% endblock %}

{% block body %}
    <article>
        <h1 class="title">#{{ post.id }} {{ post.title }}</h1>
        <p class="content">{{ post.body }}</p>
        <p class="time">
            <time datetime="{{ post.created_at|date:'Y-m-d' }}">Posted  {{ post.created_at|timesince }} ago</time>
        </p>
    </article>
    <p><a href="{% url 'blog:index' %}">All posts</a></p>
{% endblock %}    

templates/layouts/_footer.html
<footer class="footer text-center">
    <p>&copy; Copyright {% now "Y" %} &middot; Acme &middot; All rights reserved</p>
</footer>

templates/layouts/_nav.html
<nav class="navbar">
    <div class="wrapper">
        <a href="{% url 'home'  %}" class="navbar-brand">ACME</a>
        <ul class="navbar-right">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'blog:index' %}">Blog</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
        </ul>
    </div>
</nav>

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Acme {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block stylesheet %}
    {% endblock %}
</head>
<body>
    {% include "layouts/_nav.html" %}

    <div class="wrapper">
        {% block content %}  
        {% endblock %}

        {% include "layouts/_footer.html" %}
    </div>
    {% block javascript %} 
    {% endblock %}
</body>
</html>

templates/pages/about.html
{% extends 'layouts/base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <h2>About</h2>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Architecto repellat quis fuga inventore, iusto saepe, ea quo quos 
        unde magni doloremque iure rem quibusdam voluptatem doloribus asperiores vitae sequi! Ipsa.
    </p>
{% endblock %}

templates/pages/contact.html
{% extends 'layouts/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h2>Contact ACME </h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum, alias aspernatur ratione necessitatibus fugit quam sit dolorem tenetur aperiam n
        am similique atque, ullam repellendus eum? Quas aperiam quod eligendi nobis! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam vel autem dolor sint magni, nulla saepe unde provident pariatur porro vero recusandae distinctio, placeat corrupti ipsam. 
        Necessitatibus obcaecati sapiente veniam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum reprehenderit odio laboriosam porro doloremque quidem a aliquid autem voluptatem praesentium. Iste sit ipsa debitis odit nostrum temporibus blanditiis enim distinctio!
        Iste, facere? Eius dolorum ullam veritatis hic recusandae itaque eligendi est dignissimos quam, animi nesciunt at, autem minus ipsum! Neque obcaecati quo ad sint natus doloremque repellat fugiat quisquam illum.
        Illo, esse exercitationem? Soluta expedita, odit mollitia perspiciatis quod deserunt quas molestiae magnam totam eaque omnis iste eum consequatur, fugit natus! Nostrum, adipisci distinctio omnis quo voluptatum harum. Unde, amet.
        Pariatur impedit reiciendis soluta est accusamus et in laborum perferendis quibusdam. Pariatur, voluptate, architecto voluptates eaque quam, officiis aut est nemo velit illo qui tempora vel. Illum ducimus maiores voluptate!
    </p>
{% endblock %}    

templates/pages/home.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h2>Hello ACME</h2>
    <p><a href="{% url 'blog:index' %}">Visit our Blog</a></p>
{% endblock %}